// <auto-generated />
namespace HotelWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SecondEdit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondEdit));
        
        string IMigrationMetadata.Id
        {
            get { return "202009062101314_SecondEdit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
